/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agenda.view;

import br.com.agenda.controller.JframePainelController;
import br.com.agenda.helper.FormataCamposHelper;
import br.com.agenda.model.Contato;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import br.com.agenda.helper.JframePainelHelper;
import java.text.ParseException;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author loboMal
 */
public class JframePainel extends javax.swing.JFrame {

    private final JframePainelController controller;
    
    /**
     * Creates new form JframePainel
     */
    public JframePainel() {
        //Inicializa os componentes, feito pelo netbeans
        initComponents();
        
        //Carrega o controller, Formata campos - feito por mim
        this.controller = new JframePainelController(this);
        
        FormataCamposHelper formataCamposHelper = new FormataCamposHelper();
        
        // para impedir caracteres não numéricos no campo idade
        //JFormattedIdade.setDocument(formataCamposHelper);
        
        // Para colocar texto de placeholder no input de pesquisa do modal de edição de contatos
        formataCamposHelper.addPlaceholder (this.jTextFieldDePesquisaNoEditarContatos, "Pesquisar nome ou id...");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAlterarContatos = new javax.swing.JDialog();
        jPanelPrincipalDoModalAlteracao = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDePesquisaNoEditarContatos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonProcurarNoModalAlteracaoDeContatos = new javax.swing.JButton();
        scrollDoModal = new javax.swing.JScrollPane();
        tabelaDoModal = new javax.swing.JTable();
        jButtonExcluirModAlteracao = new javax.swing.JButton();
        jButtonEditarModAlteracao = new javax.swing.JButton();
        jDialogEditarContatosDentroDeAlterarContatos = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNomeModalEdit = new javax.swing.JTextField();
        jButtonEditarDoModalEditarDentroDoModalAlteracao = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldIdModalEdit = new javax.swing.JTextField();
        jFormattedTextFieldDataNascimentoModalEdit = new javax.swing.JFormattedTextField();
        JFormattedTextFieldIdadeModalEdit = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContatos = new javax.swing.JTable();
        jButtonAtualizarTabela = new javax.swing.JButton();
        jButtonPretendeAlterar = new javax.swing.JButton();
        JFormattedDataNascimento = new javax.swing.JFormattedTextField();
        JFormattedIdade = new javax.swing.JFormattedTextField();
        JFormattedNome = new javax.swing.JFormattedTextField();

        jDialogAlterarContatos.setMinimumSize(new java.awt.Dimension(632, 421));

        jPanelPrincipalDoModalAlteracao.setMinimumSize(new java.awt.Dimension(301, 212));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Alteração de Contatos:");

        jTextFieldDePesquisaNoEditarContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDePesquisaNoEditarContatosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Pesquisar contato:");

        jButtonProcurarNoModalAlteracaoDeContatos.setText("Pesquisar");
        jButtonProcurarNoModalAlteracaoDeContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarNoModalAlteracaoDeContatosActionPerformed(evt);
            }
        });

        tabelaDoModal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollDoModal.setViewportView(tabelaDoModal);
        //Criação das colunas
        String[] colunas = new String[] {"Id:", "Nome:", "Idade:", "Data de Nascimento:"};
        //Colocado por mim, para impedir a edição da linha
        tabelaDoModal.setModel(new DefaultTableModel(new Object [][] {}, colunas) {

            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @Override
            public boolean isCellEditable (int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

        });
        //Adicição do evento de duplo clique na linha da tabela do modal
        tabelaDoModal.addMouseListener(new MouseAdapter () {
            public void mouseClicked (MouseEvent e) {
                if (e.getClickCount() == 2) {
                    controller.helper.passarResultadosDaTabelaParaModalDentroDoModal();
                }
            }
        });

        jButtonExcluirModAlteracao.setBackground(new java.awt.Color(245, 55, 55));
        jButtonExcluirModAlteracao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluirModAlteracao.setText("Excluir");
        jButtonExcluirModAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirModAlteracaoActionPerformed(evt);
            }
        });

        jButtonEditarModAlteracao.setBackground(new java.awt.Color(51, 102, 255));
        jButtonEditarModAlteracao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarModAlteracao.setText("Editar");
        jButtonEditarModAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarModAlteracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalDoModalAlteracaoLayout = new javax.swing.GroupLayout(jPanelPrincipalDoModalAlteracao);
        jPanelPrincipalDoModalAlteracao.setLayout(jPanelPrincipalDoModalAlteracaoLayout);
        jPanelPrincipalDoModalAlteracaoLayout.setHorizontalGroup(
            jPanelPrincipalDoModalAlteracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalDoModalAlteracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalDoModalAlteracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollDoModal, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalDoModalAlteracaoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEditarModAlteracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirModAlteracao))
                    .addGroup(jPanelPrincipalDoModalAlteracaoLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalDoModalAlteracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanelPrincipalDoModalAlteracaoLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDePesquisaNoEditarContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonProcurarNoModalAlteracaoDeContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPrincipalDoModalAlteracaoLayout.setVerticalGroup(
            jPanelPrincipalDoModalAlteracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalDoModalAlteracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanelPrincipalDoModalAlteracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDePesquisaNoEditarContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProcurarNoModalAlteracaoDeContatos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelPrincipalDoModalAlteracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluirModAlteracao)
                    .addComponent(jButtonEditarModAlteracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDoModal, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialogAlterarContatosLayout = new javax.swing.GroupLayout(jDialogAlterarContatos.getContentPane());
        jDialogAlterarContatos.getContentPane().setLayout(jDialogAlterarContatosLayout);
        jDialogAlterarContatosLayout.setHorizontalGroup(
            jDialogAlterarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalDoModalAlteracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogAlterarContatosLayout.setVerticalGroup(
            jDialogAlterarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalDoModalAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDialogEditarContatosDentroDeAlterarContatos.setMaximumSize(null);
        jDialogEditarContatosDentroDeAlterarContatos.setMinimumSize(new java.awt.Dimension(500, 350));
        jDialogEditarContatosDentroDeAlterarContatos.setModal(true);
        jDialogEditarContatosDentroDeAlterarContatos.setPreferredSize(new java.awt.Dimension(500, 350));

        jPanel2.setMaximumSize(null);
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 350));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 350));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Editar Contato:");

        jLabel10.setText("Nome:");

        jLabel11.setText("Idade:");

        jLabel12.setText("Data de Nasc:");

        jTextFieldNomeModalEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeModalEditActionPerformed(evt);
            }
        });

        jButtonEditarDoModalEditarDentroDoModalAlteracao.setText("Editar");
        jButtonEditarDoModalEditarDentroDoModalAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarDoModalEditarDentroDoModalAlteracaoActionPerformed(evt);
            }
        });

        jLabel13.setText("Identificação:");

        jTextFieldIdModalEdit.setEditable(false);

        jFormattedTextFieldDataNascimentoModalEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataNascimentoModalEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(321, 321, 321))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEditarDoModalEditarDentroDoModalAlteracao, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                            .addComponent(jTextFieldNomeModalEdit)
                            .addComponent(jTextFieldIdModalEdit)
                            .addComponent(jFormattedTextFieldDataNascimentoModalEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                            .addComponent(JFormattedTextFieldIdadeModalEdit))))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldIdModalEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldNomeModalEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JFormattedTextFieldIdadeModalEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jFormattedTextFieldDataNascimentoModalEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonEditarDoModalEditarDentroDoModalAlteracao)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        try {
            MaskFormatter mask = new MaskFormatter ("##/##/####");
            mask.install(jFormattedTextFieldDataNascimentoModalEdit);
        }catch (ParseException pe) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo data de nascimento.", "ERRO", JOptionPane.ERROR);
        }
        try {
            MaskFormatter mask = new MaskFormatter ("###");
            mask.install(JFormattedTextFieldIdadeModalEdit);
        }catch (ParseException pe) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo idade.", "ERRO", JOptionPane.ERROR);
        }

        javax.swing.GroupLayout jDialogEditarContatosDentroDeAlterarContatosLayout = new javax.swing.GroupLayout(jDialogEditarContatosDentroDeAlterarContatos.getContentPane());
        jDialogEditarContatosDentroDeAlterarContatos.getContentPane().setLayout(jDialogEditarContatosDentroDeAlterarContatosLayout);
        jDialogEditarContatosDentroDeAlterarContatosLayout.setHorizontalGroup(
            jDialogEditarContatosDentroDeAlterarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogEditarContatosDentroDeAlterarContatosLayout.setVerticalGroup(
            jDialogEditarContatosDentroDeAlterarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CRUD EM JAVA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("nome");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("idade");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Data de Nascimento");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Contatos salvos no banco:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Formulário para envio - salvar um contato no banco");

        jTableContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "idade", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableContatos);

        jButtonAtualizarTabela.setText("Atualizar");
        jButtonAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarTabelaActionPerformed(evt);
            }
        });

        jButtonPretendeAlterar.setText("Ação");
        jButtonPretendeAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretendeAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(335, 335, 335)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 288, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JFormattedNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(JFormattedIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JFormattedDataNascimento))
                                        .addGap(15, 15, 15)
                                        .addComponent(jButton1)
                                        .addGap(0, 245, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonPretendeAlterar)))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAtualizarTabela)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(JFormattedDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JFormattedIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JFormattedNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonAtualizarTabela)
                    .addComponent(jButtonPretendeAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        //Para permitir apenas formato de data, nada mais além disso!
        try {
            MaskFormatter mask = new MaskFormatter ("##/##/####");
            mask.install(JFormattedDataNascimento);
        }catch (ParseException pe) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo data de nascimento.", "ERRO", JOptionPane.ERROR);
        }
        try {
            MaskFormatter mask = new MaskFormatter ("###");
            mask.install(JFormattedIdade);
        }catch (ParseException pe) {
            JOptionPane.showMessageDialog(null, "Erro ao formatar campo idade.", "ERRO", JOptionPane.ERROR);
        }

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Solicita o Cadastro do Contato
        this.controller.cadastrarContatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarTabelaActionPerformed
        // TODO add your handling code here:
        this.controller.atualizaTabela();
    }//GEN-LAST:event_jButtonAtualizarTabelaActionPerformed

    private void jButtonPretendeAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretendeAlterarActionPerformed
        // TODO add your handling code here:
        this.jDialogAlterarContatos.setLocationRelativeTo(this);
        this.jDialogAlterarContatos.setVisible(true);
    }//GEN-LAST:event_jButtonPretendeAlterarActionPerformed

    private void jButtonProcurarNoModalAlteracaoDeContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarNoModalAlteracaoDeContatosActionPerformed
        // TODO add your handling code here:
        this.controller.solicitaPesquisaDeContatos ();
    }//GEN-LAST:event_jButtonProcurarNoModalAlteracaoDeContatosActionPerformed

    private void jTextFieldDePesquisaNoEditarContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDePesquisaNoEditarContatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDePesquisaNoEditarContatosActionPerformed

    private void jTextFieldNomeModalEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeModalEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeModalEditActionPerformed

    private void jButtonEditarDoModalEditarDentroDoModalAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarDoModalEditarDentroDoModalAlteracaoActionPerformed
        // TODO add your handling code here:
        this.controller.solicitaAtualizacaoDoContato();
    }//GEN-LAST:event_jButtonEditarDoModalEditarDentroDoModalAlteracaoActionPerformed

    private void jFormattedTextFieldDataNascimentoModalEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataNascimentoModalEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataNascimentoModalEditActionPerformed

    private void jButtonEditarModAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarModAlteracaoActionPerformed
        // TODO add your handling code here:
        this.controller.helper.passarResultadosDaTabelaParaModalDentroDoModal();
    }//GEN-LAST:event_jButtonEditarModAlteracaoActionPerformed

    private void jButtonExcluirModAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirModAlteracaoActionPerformed
        // TODO add your handling code here:
        this.controller.solicitaExclusaoDeContato();
    }//GEN-LAST:event_jButtonExcluirModAlteracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JframePainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JframePainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JframePainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JframePainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JframePainel().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField JFormattedDataNascimento;
    private javax.swing.JFormattedTextField JFormattedIdade;
    private javax.swing.JFormattedTextField JFormattedNome;
    private javax.swing.JFormattedTextField JFormattedTextFieldIdadeModalEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAtualizarTabela;
    private javax.swing.JButton jButtonEditarDoModalEditarDentroDoModalAlteracao;
    private javax.swing.JButton jButtonEditarModAlteracao;
    private javax.swing.JButton jButtonExcluirModAlteracao;
    private javax.swing.JButton jButtonPretendeAlterar;
    private javax.swing.JButton jButtonProcurarNoModalAlteracaoDeContatos;
    private javax.swing.JDialog jDialogAlterarContatos;
    private javax.swing.JDialog jDialogEditarContatosDentroDeAlterarContatos;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNascimentoModalEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPrincipalDoModalAlteracao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableContatos;
    private javax.swing.JTextField jTextFieldDePesquisaNoEditarContatos;
    private javax.swing.JTextField jTextFieldIdModalEdit;
    private javax.swing.JTextField jTextFieldNomeModalEdit;
    private javax.swing.JScrollPane scrollDoModal;
    private javax.swing.JTable tabelaDoModal;
    // End of variables declaration//GEN-END:variables


    public JFormattedTextField getJFormattedDataNascimento() {
        return JFormattedDataNascimento;
    }

    public void setJFormattedDataNascimento(JFormattedTextField JFormattedDataNascimento) {
        this.JFormattedDataNascimento = JFormattedDataNascimento;
    }
    
    public JFormattedTextField getInputIdade () {
        return JFormattedIdade;
    }
    public void setInputIdade (JFormattedTextField inputIdade) {    
        this.JFormattedIdade = inputIdade;
    }

    public JFormattedTextField getJFormattedNome() {
        return JFormattedNome;
    }

    public void setJFormattedNome(JFormattedTextField JFormattedNome) {
        this.JFormattedNome = JFormattedNome;
    }

    public JFormattedTextField getJFormattedIdade() {
        return JFormattedIdade;
    }

    public void setJFormattedIdade(JFormattedTextField JFormattedIdade) {
        this.JFormattedIdade = JFormattedIdade;
    }
    
    
    
    public JTable getjTableContatos() {
        return jTableContatos;
    }

    public void setjTableContatos(JTable jTableContatos) {
        this.jTableContatos = jTableContatos;
    }

    public JTextField getjTextFieldDePesquisaNoEditarContatos() {
        return jTextFieldDePesquisaNoEditarContatos;
    }

    public void setjTextFieldDePesquisaNoEditarContatos(JTextField jTableDoModalAlterarContatos) {
        this.jTextFieldDePesquisaNoEditarContatos = jTableDoModalAlterarContatos;
    }

    public JPanel getjPanelPrincipalDoModalAlteracao() {
        return jPanelPrincipalDoModalAlteracao;
    }

    public void setjPanelPrincipalDoModalAlteracao(JPanel jPanelPrincipalDoModalAlteracao) {
        this.jPanelPrincipalDoModalAlteracao = jPanelPrincipalDoModalAlteracao;
    }

    public JTable getTabelaDoModal() {
        return tabelaDoModal;
    }

    public void setTabelaDoModal(JTable tabelaDoModal) {
        this.tabelaDoModal = tabelaDoModal;
    }

    public JScrollPane getScrollDoModal() {
        return scrollDoModal;
    }

    public void setScrollDoModal(JScrollPane scrollDoModal) {
        this.scrollDoModal = scrollDoModal;
    }

    public JDialog getjDialogEditarContatosDentroDeAlterarContatos() {
        return jDialogEditarContatosDentroDeAlterarContatos;
    }

    public void setjDialogEditarContatosDentroDeAlterarContatos(JDialog jDialogEditarContatosDentroDeAlterarContatos) {
        this.jDialogEditarContatosDentroDeAlterarContatos = jDialogEditarContatosDentroDeAlterarContatos;
    }
    
    public JFormattedTextField getjFormattedTextFieldDataNascimentoModalEdit() {
        return jFormattedTextFieldDataNascimentoModalEdit;
    }

    public void setjFormattedTextFieldDataNascimentoModalEdit(JFormattedTextField jFormattedTextFieldDataNascimentoModalEdit) {
        this.jFormattedTextFieldDataNascimentoModalEdit = jFormattedTextFieldDataNascimentoModalEdit;
    }
    
    public JFormattedTextField getJFormattedTextFieldIdadeModalEdit() {
        return JFormattedTextFieldIdadeModalEdit;
    }

    public void setJFormattedTextFieldIdadeModalEdit(JFormattedTextField JFormattedTextFieldIdadeModalEdit) {
        this.JFormattedTextFieldIdadeModalEdit = JFormattedTextFieldIdadeModalEdit;
    }
    

    public JTextField getjTextFieldNomeModalEdit() {
        return jTextFieldNomeModalEdit;
    }

    public void setjTextFieldNomeModalEdit(JTextField jTextFieldNomeModalEdit) {
        this.jTextFieldNomeModalEdit = jTextFieldNomeModalEdit;
    }

    public JTextField getjTextFieldIdModalEdit() {
        return jTextFieldIdModalEdit;
    }

    public void setjTextFieldIdModalEdit(JTextField jTextFieldIdModalEdit) {
        this.jTextFieldIdModalEdit = jTextFieldIdModalEdit;
    }

    
    
}
